In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.2'

In [4]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv    

--2025-09-28 23:14:56--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: 'car_fuel_efficiency.csv.1'

     0K .......... .......... .......... .......... ..........  5% 1.94M 0s
    50K .......... .......... .......... .......... .......... 11% 1.80M 0s
   100K .......... .......... .......... .......... .......... 17% 3.55M 0s
   150K .......... .......... .......... .......... .......... 23% 8.97M 0s
   200K .......... .......... .......... .......... .......... 29% 5.24M 0s
   250K .......... .......... .......... .......... .......... 35% 4.99M 0s
   300K .......... .......... .......... .......... .......... 40% 7.88M 0s
   350K

In [5]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [6]:
len(df)

9704

In [7]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [8]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [9]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [10]:
df.loc[df['origin'] == 'Asia'].fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

In [11]:
df['horsepower'].median()

np.float64(149.0)

In [12]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [13]:
updated_df = df.fillna(value=df['horsepower'].mode())

In [14]:
updated_df['horsepower'].median()

np.float64(149.0)

In [15]:
asian_cars_df = df.loc[df['origin'] == 'Asia']

In [16]:
asian_cars_df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [17]:
weight_model_year_df =df.loc[:, ["vehicle_weight", "model_year"]]

In [18]:
first_seven_rows = weight_model_year_df.head(7)

In [19]:
first_seven_rows

vehicle_weight  model_year
0     3413.433759        2003
1     3149.664934        2007
2     3079.038997        2018
3     2542.392402        2009
4     3460.870990        2009
5     2484.883986        2008
6     3006.542287        2012

In [20]:
X = first_seven_rows.to_numpy()

In [21]:
X

array([[3413.43375861, 2003.        ],
       [3149.66493422, 2007.        ],
       [3079.03899737, 2018.        ],
       [2542.39240183, 2009.        ],
       [3460.87098999, 2009.        ],
       [2484.88398604, 2008.        ],
       [3006.54228722, 2012.        ]])

In [22]:
X.T

array([[3413.43375861, 3149.66493422, 3079.03899737, 2542.39240183,
        3460.87098999, 2484.88398604, 3006.54228722],
       [2003.        , 2007.        , 2018.        , 2009.        ,
        2009.        , 2008.        , 2012.        ]])

In [23]:
import numpy as np

In [24]:
XTX = X.T @ X

In [25]:
XTX 

array([[64707732.45267162, 42471352.31816065],
       [42471352.31816065, 28264752.        ]])

In [26]:
inverse_XTX = np.linalg.inv(XTX)

In [27]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [36]:
XTX_Xtranspose_multiplied = inverse_XTX @ X.T

In [37]:
XTX_Xtranspose_multiplied

array([[ 4.53988137e-04,  1.50583226e-04,  5.25653323e-05,
        -5.35760232e-04,  4.97198506e-04, -5.98746643e-04,
        -1.88279553e-05],
       [-6.11308746e-04, -1.55263108e-04, -7.58969157e-06,
         8.76125202e-04, -6.76025493e-04,  9.70734844e-04,
         9.94754429e-05]])

In [38]:
w = XTX_Xtranspose_multiplied @ y

In [39]:
total_sum = np.sum(w)

In [40]:
total_sum

np.float64(0.4903094879707426)